title: Coline # your site title
author: GitHub User
email: your-email@domain.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cpti372.github.io/" 
twitter_username: ColineYeonsuKim # replace with your_twitter_username or comment to remove link from footer
github_username:  cpti372 # replace with your_github_username or comment to remove link from footer
instagram_username: colinekim_dream # replace with your_instagram_username or comment to remove link from footer
social:
  name: Coline Kim 
  links:
    - https://twitter.com/ColineYeonsuKim
    - https://www.facebook.com/yeonsu.kim.756
    - https://www.linkedin.com/in/smartcitysue2020
    - https://github.com/cpti372
    - https://www.instagram.com/colinekim_dream/

disqus:
  shortname: disqus_XoxI2yKCpS # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
